### ISSUE TITLE
Not handling Indic characters

### ISSUE THREAD

**Issue by kotpal** [nota/split-graphemes#4]
Looks like this is by design. Are there any plans to handle Indic and other complex scripts?

**Comment by hiroshi** [comment]
ping @daiiz

**Comment by daiiz** [comment]
@kotpal At the moment there is no such plan. However, it is an extensible design by adding a corresponding regular expression for each letters.

**Comment by kotpal** [comment]
Ok. Thank you @daiiz . Unfortunately, it is not going to be a simple regex.

**Comment by rakusai** [comment]
@kotpal 
Brahmic (Indic) scripts is a name of category in Unicode.
Which script do you want to handle?
Check out the list here.
https://en.wikipedia.org/wiki/List_of_Unicode_characters#Brahmic_(Indic)_scripts
as you can see our source code, it's not so complex to support them.

**Comment by rakusai** [comment]
@kotpal we have fixed the issue! https://github.com/nota/split-graphemes/pull/5

**Comment by kotpal** [comment]
@rakusai Awesome! I saw the fix and it is was simple. It is a testament on how flexible split-graphemes was architected - so as to add support to even complex scripts so seamlessly and easily. Hat tip. 

Note: I will add support to some missing Indic languages - like Kannada, Malayalam etc and send a PR (when I get the chance).

**Comment by rakusai** [comment]
Yes, as far as I researched, Gujarati, Kannada, Malayalam, Oriya are all Brahmic family, so we can easily support.
